### ISSUE TITLE
Script 1 - Data Transformation 

### ISSUE THREAD

**Issue by thayeylolu** [UBC-MDS/credit_default_prediction#19]
While attempting to create script 2, I made the following observation

- The existing dataset does not have the (X1...X23) columns so I did not drop the top row
- I was unable to download the data set using the command line arguments for the  `download_data.py` . 
- I am unsure if I am to apply transformation to the whole data set or just the train data set. Regardless, I applied transformation to the train dataset alone and saved the test data set in a new folder
- I appended the`target` column to the transformed dataset and saved it in a new file.
- Unsure if I am to include documentation in my main function

**Comment by karanpreetkaur** [comment]
**Try running below** for data download script in your command
- Through command line access the path where you have the script 

python download_data.py --out_type="csv" --url="https://archive.ics.uci.edu/ml/machine-learning-databases/00350/default%20of%20credit%20card%20clients.xls" --out_file="**C:\Users\hp\Documents\Personal Documents\test.csv**" 

 Change the --out_file path above where you want to store the file.

- I think we should transform train and test data separately after splitting and save it as .csv . I will read those csv in my script for model building and testing

- In my belief, the transformed data should not have `target` column. You can save targets (for train and test) in separate file.

@liannah @Arushi282 please add to this if you have any comments.

**Comment by Arushi282** [comment]
Yeah I agree with @karanpreetkaur, I think the preprocessing script should output 5 different cvs:  X_train (not transformed), X_train (transformed), y_train, X_test and y_test. 

X_train (not transformed) will be used by me in the Data viz script 

and  X_train (transformed), y_train, X_test and y_test will be used by @karanpreetkaur in predictive analysis script. 

Yeah I also agree that X_train (transformed) should not contain the target column. 

Please let me know if this sounds good to you guys

**Comment by Arushi282** [comment]
Also for your last point @thayeylolu, I am unsure about this as well, I would suggest we ask this in lab on Thursday or during office hrs.

**Comment by thayeylolu** [comment]
> 

Thanks @liannah . I was using the wrong slash

**Comment by thayeylolu** [comment]
I will be including the Shebang (#!/usr/bin/env python) in the download_data.py ,  Its not executable without it for some reason. @liannah  and @KaranpreetKaur

**Comment by thayeylolu** [comment]
I also included a Yaml file, because I need an environment with all the packages. I will add it in gitignore for now.

**Comment by thayeylolu** [comment]
The PR can be found here: #20  I have included suggested corrections and additions.

**Comment by thayeylolu** [comment]
Regarding this part of the task
`A second script that reads the data from the first script  : I ran the first script as a subprocess in the second script. It does not "read the data from the first script". It only runs it. Do you guys have another understanding of what is meant by "read data from the first script"?

**Comment by liannah** [comment]
Sorry guys, that I am late with this discussion. I think that in Tiffanys file she had what Taiwo had in the first place with test and train sets, that should have been good enough, but if you think we should get target column out that is fine as well. As long as it will not cause any trouble during modeling. @karanpreetkaur 

And also we need doctsrings for each file. 

Also I think you can put yaml file in the root folder, I think we are all going to need it and eventually will need it there.  

As for the last part, I will add a comment in the file. As i think refers to the fact that the script should be ran after first script, and the user needs to do it. So in this script we need to assume the data is already downloaded. @thayeylolu

**Comment by Arushi282** [comment]
> Regarding this part of the task `A second script that reads the data from the first script : I ran the first script as a subprocess in the second script. It does not "read the data from the first script". It only runs it. Do you guys have another understanding of what is meant by "read data from the first script"?

Once the data is saved as a csv after running the first script, the second script should take the file path of that csv and use it . @karanpreetkaur @liannah  please confirm this.

**Comment by liannah** [comment]
I think this was confirmed by Tiffany on slack. Refering to that message answer: 

You call each script separately this week and document how in the README.md file (like this example: https://github.com/ttimbers/breast_cancer_predictor/tree/v2.0#usage) and then next week you will create a pipeline to automate this using GNU Make (for example: https://github.com/ttimbers/breast_cancer_predictor/blob/v3.0/Makefile) 

@thayeylolu @Arushi282 @karanpreetkaur

**Comment by Arushi282** [comment]
Yep sounds good! We'll work on this tomorrow

**Comment by Arushi282** [comment]
> Sorry guys, that I am late with this discussion. I think that in Tiffanys file she had what Taiwo had in the first place with test and train sets, that should have been good enough, but if you think we should get target column out that is fine as well. As long as it will not cause any trouble during modeling. @karanpreetkaur
> 
> And also we need doctsrings for each file.
> 
> Also I think you can put yaml file in the root folder, I think we are all going to need it and eventually will need it there.
> 
> As for the last part, I will add a comment in the file. As i think refers to the fact that the script should be ran after first script, and the user needs to do it. So in this script we need to assume the data is already downloaded. @thayeylolu

Also I think you are right @liannah. Sorry I think I got confused with separating the code and scripts. I just reviewed my notes from 573 and 571. And I think we should just split the data into train_df and test_df and create the preprocessor (column transformer) in the 2nd script. Then I will use the train_df in data viz and @karanpreetkaur will use the train_df and test_df and the preprocessor, she will make a pipeline with the preprocessor and use that for cross-validation, fit and predict. I don't think we have to actually transform the data in the second script, it should just be the initial cleaning and set up for making the model. 

In the Breast cancer sample provided by Tiffany, she scales the data in the preprocessing script and then uses that pre processed data to predict her model, but she is also doing her analysis in r. For us it would make more sense to use a pipeline with a column transformer and the SVC model, and use that on the train_df (which will be split into X_test and y_test in the 4th script itself). 

My only question is how will we save the column transformer we create in the 2nd script? 

let me know if any of this makes sense, sorry for the confusion! 

@karanpreetkaur @liannah @thayeylolu

**Comment by liannah** [comment]
I believe, we need to perform preprocessing here by preprocessing I mean OHE, scaling, etc. As it makes more sense to do it here with train and test data. So, we need to create it with make_column_transformer and then call it in main function, do fit_transform on train data and just transform on test data. 

Let me know if you think this approach is incorrect. @thayeylolu @Arushi282 @karanpreetkaur

**Comment by liannah** [comment]
Also, @thayeylolu do you specify in your script where to save this files ?

**Comment by thayeylolu** [comment]
@liannah . I have not specified that yet.

**Comment by thayeylolu** [comment]
I also noticed tiffany's r code is appended y_train and y_test after scaling? Are we all good with that? @Arushi282 @karanpreetkaur @liannah

**Comment by liannah** [comment]
I am good. As I think it should be preprocessed there. And we need to do eda on preprocessed train dataset, like getting correlation matrix and counting how many yes, nos are there in the target. Something like that @thayeylolu @Arushi282 @karanpreetkaur 

Yeah, I just wanted to make sure, that we have preprocess and raw folder for downloaded data. 

I guess, if others confirm, we can merge this script and then polish it later.

**Comment by thayeylolu** [comment]
I've made recommend changes.
